// SPDX-License-Identifier: GPL-3.0-only
/*
 *  Extreme Launcher - Minecraft Launcher
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, version 3.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 * HOW THE MURMUR2 VECTORS WERE PRODUCED, because it matters for how much they are worth.
 *
 * Upstream has no test for this hash, so there was nothing to inherit. Asserting the C# against
 * itself would prove only that it is self-consistent, which is exactly the failure mode that let four
 * defects through the last time. So testdata/murmur2-vectors.txt was generated by a SECOND
 * transcription of libraries/murmur2/src/MurmurHash2.cpp, written in Python straight from the C++
 * without reference to the C#; that script is kept beside the vectors as murmur2-vectors.py so the
 * claim can be re-checked. Two independent readings of the same source agreeing on 25 inputs -- empty,
 * every length modulo four, whitespace-only, and cases past the read buffer -- is real evidence. It is
 * still not a fingerprint CurseForge has confirmed; only a real jar checked against their API would be
 * that, and that is noted in PORTING.md rather than pretended away here.
 */

using System.Text;
using Xunit;

namespace ExtremeLauncher.ModPlatform.Tests;

public sealed class Murmur2Tests
{
    public static TheoryData<string, uint> Vectors()
    {
        var data = new TheoryData<string, uint>();

        foreach (var line in File.ReadAllLines(Path.Combine("testdata", "murmur2-vectors.txt")))
        {
            if (line.Length == 0)
            {
                continue;
            }

            var split = line.LastIndexOf(' ');

            data.Add(line[..split], uint.Parse(line[(split + 1)..], System.Globalization.CultureInfo.InvariantCulture));
        }

        return data;
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void MatchesAnIndependentTranscriptionOfTheCppAlgorithm(string inputHex, uint expected)
    {
        var input = Convert.FromHexString(inputHex);

        Assert.Equal(expected, Murmur2.Hash(input));

        // The streaming path has to agree with the in-memory one; it is the one that actually runs.
        using var stream = new MemoryStream(input);
        Assert.Equal(expected, Murmur2.Hash(stream));
    }

    [Fact]
    public void TheVectorsCoverEveryLengthModuloFour()
    {
        var lengths = Vectors()
            .Select(row => ((string)row[0]).Length / 2 % 4)
            .Distinct()
            .ToList();

        // The tail mix has four branches and each one has to be exercised by something.
        Assert.Equal(4, lengths.Count);
    }

    /*
     * The whole reason CurseForge's fingerprint is not stock murmur2. A jar rebuilt on another
     * platform, or a text file with converted line endings, has to fingerprint the same or every
     * lookup misses.
     */
    [Theory]
    [InlineData("abcd", "a b\tc\r\nd")]
    [InlineData("abcd", " abcd ")]
    [InlineData("", " \t\r\n ")]
    public void WhitespaceIsInvisibleToTheHash(string plain, string spaced)
        => Assert.Equal(
            Murmur2.Hash(Encoding.UTF8.GetBytes(plain)),
            Murmur2.Hash(Encoding.UTF8.GetBytes(spaced)));

    /// <summary>The four bytes stripped, and only those four.</summary>
    [Fact]
    public void OnlyTabLineFeedCarriageReturnAndSpaceAreStripped()
    {
        for (var c = 0; c < 256; c++)
        {
            Assert.Equal(c is 9 or 10 or 13 or 32, Murmur2.IsFilteredOut((byte)c));
        }

        // Vertical tab and form feed look like whitespace and are not filtered.
        Assert.False(Murmur2.IsFilteredOut(11));
        Assert.False(Murmur2.IsFilteredOut(12));
    }

    /*
     * The seed comes from the FILTERED length, so the whole input is measured before any of it is
     * mixed. Reading it in chunks must not change that -- which is what a buffer boundary landing
     * mid-group would break.
     */
    [Fact]
    public void ChunkedReadsGiveTheSameAnswerAsOneRead()
    {
        var input = new byte[10_000];

        for (var i = 0; i < input.Length; i++)
        {
            // Includes bytes that get filtered, so the boundaries fall in awkward places.
            input[i] = (byte)(i * 7 % 256);
        }

        var expected = Murmur2.Hash(input);

        foreach (var bufferSize in (ReadOnlySpan<int>)[4, 5, 7, 64, 999, 10_000, 65_536])
        {
            using var stream = new MemoryStream(input);

            Assert.Equal(expected, Murmur2.Hash(stream, filterOut: null, bufferSize));
        }
    }

    [Fact]
    public void AStreamThatCannotSeekIsRefusedRatherThanHashedWrongly()
    {
        using var stream = new UnseekableStream([1, 2, 3, 4]);

        // Silently hashing the first pass only would produce a confident, wrong fingerprint.
        Assert.Throws<ArgumentException>(() => Murmur2.Hash(stream));
    }

    private sealed class UnseekableStream(byte[] data) : MemoryStream(data)
    {
        public override bool CanSeek => false;
    }
}

public sealed class HashingTests : IDisposable
{
    private readonly string _temp = Path.Combine(Path.GetTempPath(), "el-hash-" + Guid.NewGuid().ToString("N"));

    public HashingTests() => Directory.CreateDirectory(_temp);

    public void Dispose()
    {
        try
        {
            Directory.Delete(_temp, recursive: true);
        }
        catch (IOException)
        {
            // Best effort.
        }
    }

    [Theory]
    [InlineData(HashAlgorithm.Md4, "md4")]
    [InlineData(HashAlgorithm.Md5, "md5")]
    [InlineData(HashAlgorithm.Sha1, "sha1")]
    [InlineData(HashAlgorithm.Sha256, "sha256")]
    [InlineData(HashAlgorithm.Sha512, "sha512")]
    [InlineData(HashAlgorithm.Murmur2, "murmur2")]
    public void AlgorithmNamesRoundTrip(HashAlgorithm algorithm, string text)
    {
        Assert.Equal(text, Hashing.AlgorithmToString(algorithm));
        Assert.Equal(algorithm, Hashing.AlgorithmFromString(text));
    }

    [Theory]
    [InlineData("")]
    [InlineData("SHA1")]
    [InlineData("crc32")]
    public void AnUnrecognisedAlgorithmIsUnknown(string text)
        => Assert.Equal(HashAlgorithm.Unknown, Hashing.AlgorithmFromString(text));

    /*
     * Modrinth takes the first entry of its capabilities list; CurseForge does NOT, and upstream is
     * right. That list is what the API reports hashes in -- sha1 first -- but identifying an unknown
     * local file goes to the fingerprint endpoint, which only understands murmur2.
     */
    [Fact]
    public void EachProviderIdentifiesFilesWithItsOwnAlgorithm()
    {
        Assert.Equal(HashAlgorithm.Sha512, Hashing.AlgorithmFor(ResourceProvider.Modrinth));
        Assert.Equal(HashAlgorithm.Murmur2, Hashing.AlgorithmFor(ResourceProvider.Flame));

        // Deliberately not the first capability, which would be sha1.
        Assert.Equal("sha1", ProviderCapabilities.HashTypes(ResourceProvider.Flame)[0]);
    }

    [Fact]
    public void CryptographicHashesComeBackAsLowercaseHex()
    {
        var data = Encoding.UTF8.GetBytes("abc");

        Assert.Equal("a9993e364706816aba3e25717850c26c9cd0d89d", Hashing.Hash(data, HashAlgorithm.Sha1));
        Assert.Equal("900150983cd24fb0d6963f7d28e17f72", Hashing.Hash(data, HashAlgorithm.Md5));
        Assert.Equal(
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            Hashing.Hash(data, HashAlgorithm.Sha256));
    }

    /// <summary>Decimal, not hex — it is a number to CurseForge, and upstream formats it with QString::number.</summary>
    [Fact]
    public void Murmur2ComesBackAsADecimalNumber()
    {
        var result = Hashing.Hash(Encoding.UTF8.GetBytes("abcd"), HashAlgorithm.Murmur2);

        Assert.Equal("3376380438", result);
        Assert.DoesNotContain(result, c => char.IsLetter(c));
    }

    [Fact]
    public void AnUnknownAlgorithmHashesToNothing()
        => Assert.Equal(string.Empty, Hashing.Hash(Encoding.UTF8.GetBytes("abc"), HashAlgorithm.Unknown));

    /// <summary>Refused rather than silently computed with a different algorithm.</summary>
    [Fact]
    public void Md4IsRefusedBecauseTheBclHasNone()
        => Assert.Throws<NotSupportedException>(
            () => Hashing.Hash(Encoding.UTF8.GetBytes("abc"), HashAlgorithm.Md4));

    [Fact]
    public void HashingAFileAgreesWithHashingItsBytes()
    {
        var path = Path.Combine(_temp, "mod.jar");
        var data = Encoding.UTF8.GetBytes("pretend this is a jar\r\n\twith whitespace");

        File.WriteAllBytes(path, data);

        foreach (var algorithm in (ReadOnlySpan<HashAlgorithm>)[HashAlgorithm.Sha1, HashAlgorithm.Sha512, HashAlgorithm.Murmur2])
        {
            Assert.Equal(Hashing.Hash(data, algorithm), Hashing.HashFile(path, algorithm));
        }
    }

    [Fact]
    public async Task TheHasherTaskReportsItsResult()
    {
        var path = Path.Combine(_temp, "mod.jar");
        await File.WriteAllTextAsync(path, "abc").ConfigureAwait(true);

        var task = new HasherTask(path, ResourceProvider.Modrinth);

        var reported = string.Empty;
        task.ResultsReady += (_, hash) => reported = hash;

        Assert.True(await task.RunAsync().ConfigureAwait(true));

        Assert.Equal(Hashing.Hash(Encoding.UTF8.GetBytes("abc"), HashAlgorithm.Sha512), task.Result);
        Assert.Equal(task.Result, reported);
    }

    /// <summary>Upstream fails on an empty hash rather than reporting success with nothing.</summary>
    [Fact]
    public async Task TheHasherTaskFailsOnAnEmptyHash()
    {
        var path = Path.Combine(_temp, "mod.jar");
        await File.WriteAllTextAsync(path, "abc").ConfigureAwait(true);

        var task = new HasherTask(path, HashAlgorithm.Unknown);

        Assert.False(await task.RunAsync().ConfigureAwait(true));
        Assert.Contains("Empty hash", task.FailReason, StringComparison.Ordinal);
    }
}
